
#ifndef __COMMAND_ID_H__
#define __COMMAND_ID_H__

namespace PhysBAM {
    typedef enum {CREATE_ENGINE, INITIALIZE_MUSCLES, INITIALIZE_MESH, INITIALIZE_ENGINE,
                  EXACT_SOLVE, DESTROY_ENGINE, DISPLACEMENT_GRID, DISPLACEMENT_MESH,
                  STRESS, STRAIN, H, CELL, NODE, PADDED_NODE_DOMAIN, UNPADDED_NODE_DOMAIN,
                  PADDED_CELL_DOMAIN, UNPADDED_CELL_DOMAIN, GET_GRID,
                  GET_CELL_TYPE, SET_CELL_TYPE, GET_CELL_TYPE_MESH, SET_CELL_TYPE_MESH,
                  GET_CELL_INDICES_MESH, SET_CELL_INDICES_MESH, GET_CELLS_MESH,
                  SET_CELLS_MESH, NUMBER_OF_MESH_CELLS, NUMBER_OF_MESH_NODES,
                  CREATE_NEW_CONSTRAINT, GET_CONSTRAINT, SET_CONSTRAINT, REMOVE_CONSTRAINT,
                  NUMBER_OF_CONSTRAINTS, GET_COLLISION_CONSTANTS, SET_COLLISION_CONSTANTS,
                  GET_COLLISION_LOCATIONS, SET_COLLISION_LOCATIONS, ENGINE_READY,
                  ENGINE_INITIALIZED, DISPLACEMENT, DEFORMATION, GET_COARSEGRID, 
                  GET_MUSCLE_DATA, SET_MUSCLE_DATA, GET_MUSCLE_ACTIVATIONS,
                  SET_MUSCLE_ACTIVATIONS, GET_MUSCLE_MAX_STRESS, SET_MUSCLE_MAX_STRESS} MPI_COMMAND_ID;

    const char* MPI_METHOD_NAMES[]={"CREATE_ENGINE", "INITIALIZE_MUSCLES", "INITIALIZE_MESH", "INITIALIZE_ENGINE",
                                    "EXACT_SOLVE", "DESTROY_ENGINE", "DISPLACEMENT_GRID", "DISPLACEMENT_MESH",
                                    "STRESS", "STRAIN", "H", "CELL", "NODE", "PADDED_NODE_DOMAIN", "UNPADDED_NODE_DOMAIN",
                                    "PADDED_CELL_DOMAIN", "UNPADDED_CELL_DOMAIN", "GET_GRID",
                                    "GET_CELL_TYPE", "SET_CELL_TYPE", "GET_CELL_TYPE_MESH", "SET_CELL_TYPE_MESH",
                                    "GET_CELL_INDICES_MESH", "SET_CELL_INDICES_MESH", "GET_CELLS_MESH",
                                    "SET_CELLS_MESH", "NUMBER_OF_MESH_CELLS", "NUMBER_OF_MESH_NODES",
                                    "CREATE_NEW_CONSTRAINT", "GET_CONSTRAINT", "SET_CONSTRAINT", "REMOVE_CONSTRAINT",
                                    "NUMBER_OF_CONSTRAINTS", "GET_COLLISION_CONSTANTS", "SET_COLLISION_CONSTANTS",
                                    "GET_COLLISION_LOCATIONS", "SET_COLLISION_LOCATIONS", "ENGINE_READY",
                                    "ENGINE_INITIALIZED", "DISPLACEMENT", "DEFORMATION", "GET_COARSEGRID",
                                    "GET_MUSCLE_DATA", "SET_MUSCLE_DATA", "GET_MUSCLE_ACTIVATIONS",
                                    "SET_MUSCLE_ACTIVATIONS", "GET_MUSCLE_MAX_STRESS", "SET_MUSCLE_MAX_STRESS", NULL };
}

#endif
