typedef VECTOR<T,d> TV;
typedef VECTOR<int,d> T_INDEX;
typedef STENCIL<T,d> T_STENCIL;
typedef GRID<TV> T_GRID;
typedef ARRAY<CELL_TYPE,T_INDEX> T_CELL_TYPE_FIELD;
typedef ARRAY<bool,T_INDEX> T_FLAG;
typedef ARRAY<T,T_INDEX> T_SCALAR_VARIABLE;
typedef VECTOR<T_SCALAR_VARIABLE,d> T_VECTOR_VARIABLE;
typedef ARRAY<MATRIX<T,d>,T_INDEX> T_MATRIX_ARRAY;
typedef ARRAY<DIAGONAL_MATRIX<T,d>,T_INDEX> T_DIAGONAL_MATRIX_ARRAY;





    
