include ../Makefile.Library.PreMatter

CXXFLAGS+=
LD_FLAGS+= 
DEPENDENCIES = 
EXT_DEPENDENCIES = -lpthread

Library_Src = PTHREAD_QUEUE.cpp
Library_Headers = POINTER_QUEUE.h PTHREAD_QUEUE.h
LIBRARY_NAME=libTQ
INCLUDE_NAME=Thread_Queueing

include ../Makefile.Library.Template

